[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/types-de-contenus/actions/"
to = "/rubrique/nos-actions/"

[[redirects]]
from = "/skol-diwan-keryann-2/"
to = "/toutes-les-fiches-pratiques-culture-et-sports/skol-diwan-keryann-2/"

[[redirects]]
from = "/agenda/archives/"
to = "/agenda/"

[[redirects]]
from = "/categories/sports/"
to = "/sports/"

[[redirects]]
from = "/liste-organisations/piscine-brequigny/"
to = "/"

[[redirects]]
from = "/piscine-saint-georges/"
to = "/"

[[redirects]]
from = "/liste-organisations/piscine-saint-georges/"
to = "/"

[[redirects]]
from = "/les-horaires-des-gymnases/"
to = "/fiches-pratiques/les-menus-des-creches/"

[[redirects]]
from = "/nos-actions/ce-que-fait-rennes-metropole-pour-le-logement/"
to = "/ce-que-fait-rennes-metropole-pour-le-logement/"

[[redirects]]
from = "/fiches-pratiques/sports-et-loisirs/"
to = "/sports-et-loisirs/"

[[redirects]]
from = "/page-chiffres-cles-et-remontee-de-personnes/"
to = "/page-appel-a-action/page-chiffres-cles-et-remontee-de-personnes/"

[[redirects]]
from = "/liste-organisations/piscine-gayeulles/"
to = "/"

[[redirects]]
from = "/equipe/guillaume-rouan/"
to = "/guillaume-rouan/"

[[redirects]]
from = "/types-de-contenus/nos-actions/"
to = "/rubrique/nos-actions/"

[[redirects]]
from = "/types-de-contenus/fiches-pratiques/"
to = "/rubrique/fiches-informations/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/equipe-editoriale/"

[[redirects]]
from = "/liste-organisations/4bis-information-jeunesse/"
to = "/4bis-information-jeunesse/"

[[redirects]]
from = "/projets/jeunesse/"
to = "/projets/cibles/jeunesse/"

[[redirects]]
from = "/fiches-pratiques/les-horaires-des-gymnases/"
to = "/fiches-pratiques/les-menus-des-creches/"

[[redirects]]
from = "/equipe/florian-guillanton/"
to = "/florian-guillanton/"

[[redirects]]
from = "/equipe/estelle-soleillant/"
to = "/estelle-soleillant/"

[[redirects]]
from = "/categories/elus-metropolitains/"
to = "/elus-metropolitains/"

[[redirects]]
from = "/organisations/4bis-information-jeunesse/"
to = "/4bis-information-jeunesse/"

[[redirects]]
from = "/types-de-contenus/"
to = "/rubrique/"

[[redirects]]
from = "/liste-organisations/"
to = "/"

[[redirects]]
from = "/equipe/matthieu-delsaut/"
to = "/matthieu-delsaut/"

[[redirects]]
from = "/les-horaires-des-piscines/"
to = "/fiches-pratiques/les-horaires-des-piscines/"

[[redirects]]
from = "/organisations/"
to = "/"

[[redirects]]
from = "/politique-de-confidentialite/"
to = "/politique-de-confidentialites/"

[[redirects]]
from = "/equipe/perrine-chaissac/"
to = "/perrine-chaissac/"

[[redirects]]
from = "/piscine-brequigny/"
to = "/"

[[redirects]]
from = "/projets/logement/"
to = "/projets/themes/logement/"

[[redirects]]
from = "/equipe/"
to = "/"

[[redirects]]
from = "/liste-organisations/categories/sports/"
to = "/sports/"

[[redirects]]
from = "/types-de-contenus/fiches-informations/"
to = "/rubrique/fiches-informations/"

[[redirects]]
from = "/types-de-contenus/fiches/"
to = "/rubrique/fiches-informations/"

[[redirects]]
from = "/actualites/"
to = "/communiques-de-presse/"

[[redirects]]
from = "/actions/"
to = "/rubrique/nos-actions/"

[[redirects]]
from = "/fiches-pratiques/aides/"
to = "/aides/"

[[redirects]]
from = "/equipe/christophe-panon/"
to = "/christophe-panon/"

[[redirects]]
from = "/fiches-pratiques/associations/"
to = "/associations/"

[[redirects]]
from = "/fiches-pratiques/culture/"
to = "/culture/"

[[redirects]]
from = "/skol-diwan-keryann/"
to = "/toutes-les-fiches-pratiques-culture-et-sports/"

[[redirects]]
from = "/piscine-gayeulles/"
to = "/"

[[redirects]]
from = "/equipe/naelle-frega/"
to = "/naelle-frega/"

